trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: windows-latest
  demands:
  - msbuild
  - visualstudio

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: PublishTestResults@1
  inputs:
    command: 'test'
    projects: '**/*.csproj'

- task: NuGet@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()